import type {
  DefectFinding,
} from '../types';
import type {
  TestLeadOrchestrationInput,
} from '../orchestration';
import type {
  OfflineScenarioFixture,
} from './offlineScenarioValidation';

const modules = [
  'authentication',
  'note_crud',
  'search',
  'file_upload',
  'sharing',
  'backup_restore',
  'logging',
  'admin_permissions',
];

const requirementsText = [
  '系统必须支持用户登录后创建、编辑、删除笔记。',
  '系统应该支持私密笔记，普通用户不能查看他人的私密笔记。',
  '系统需要支持共享笔记，被授权用户可以查看共享内容。',
  '系统必须支持按标题和正文搜索笔记。',
  '系统应该支持附件上传，并限制文件大小和类型。',
  '系统需要每天自动备份数据库。',
  '系统应该记录登录失败、保存失败、上传失败和权限拒绝日志。',
  'The system must allow 10-30 users to use the service concurrently.',
  'The system should provide a restore procedure from backup.',
].join('\n');

const existingDefects: DefectFinding[] = [
  {
    id: 'DRAFT-SNS-PRIVATE-ACCESS',
    testCaseId: 'TC-SNS-AUTHZ-PRIVATE-NOTE',
    title: 'Draft: private note can be accessed by an unauthorized user',
    actualResult: 'Unauthorized user receives HTTP 200 and private note content.',
    expectedResult: 'Unauthorized user should receive 403 or an equivalent permission denial.',
    severity: 'P0',
    affectedArea: 'authorization private notes',
    suspectedLayer: 'permission',
    evidenceIds: ['EV-SNS-PRIVATE-ACCESS-FAIL'],
    recommendation: 'Treat as draft until reproduced in a controlled environment; fix authorization filter before release.',
    status: 'open',
  },
  {
    id: 'DRAFT-SNS-UPLOAD-LIMIT',
    testCaseId: 'TC-SNS-UPLOAD-LIMIT',
    title: 'Draft: oversized attachment upload lacks clear boundary feedback',
    actualResult: 'Oversized upload fails without a clear user-facing error.',
    expectedResult: 'User should see a clear non-sensitive message about file size and type limits.',
    severity: 'P2',
    affectedArea: 'file upload',
    suspectedLayer: 'frontend',
    evidenceIds: ['EV-SNS-UPLOAD-LIMIT-FAIL'],
    recommendation: 'Add clear validation feedback and regression coverage for size/type boundaries.',
    status: 'open',
  },
  {
    id: 'DRAFT-SNS-RESTORE-EVIDENCE',
    testCaseId: 'TC-SNS-RESTORE-PROCEDURE',
    title: 'Draft: backup restore proof is missing',
    actualResult: 'Backup claim exists, but no restore record or artifact was provided.',
    expectedResult: 'Restore drill should have a dated record, source backup, operator, and verification result.',
    severity: 'P1',
    affectedArea: 'backup restore',
    suspectedLayer: 'deployment',
    evidenceIds: ['EV-SNS-RESTORE-NO-RECORD', 'EV-SNS-BACKUP-ORAL-CLAIM'],
    recommendation: 'Perform and record a restore drill before release readiness is accepted.',
    status: 'needs_evidence',
  },
];

export const smallNoteSystemOrchestrationInput: TestLeadOrchestrationInput = {
  runId: 'offline-small-note-system',
  targetSystemName: 'Small Team Notes',
  targetSystemType: 'note_system',
  systemDescription: 'A small team note system for 10-30 users with private notes, sharing, search, attachment upload, backup/restore, logging, and admin permissions.',
  requirementsText,
  modules,
  contextSources: ['agent-testing/examples/small-note-system/static-fixture'],
  knownConstraints: [
    'Fixture data is static and does not connect to a real note system.',
    'Evidence IDs are illustrative and may not match generated test case IDs.',
  ],
  opsProfile: {
    targetSystemName: 'Small Team Notes',
    targetSystemType: 'note_system',
    deploymentMode: 'single_vps',
    userScale: 'team_10_30',
    modules,
    hasAuthentication: true,
    hasAuthorization: true,
    hasFileUpload: true,
    hasSearch: true,
    hasBackup: true,
    hasRestore: true,
    hasLogging: true,
    hasMonitoring: false,
    hasPublicAccess: false,
    hasDatabase: true,
    hasExternalStorage: false,
    hasMultiUserUsage: true,
    hasAdminRole: true,
    knownOpsRisks: [
      'Restore procedure has no recorded drill evidence.',
      'Logging evidence is only agent reasoning and must be downgraded.',
    ],
  },
  rawEvidence: [
    {
      id: 'EV-SNS-LOGIN-PASS',
      testCaseId: 'TC-SNS-LOGIN',
      testScope: 'authentication login',
      executionMethod: 'static API response sample',
      executorType: 'api',
      rawResult: 'pass',
      evidenceSource: 'offline fixture API sample',
      evidenceSummary: 'POST /api/login returned 200 with a session token for a valid user.',
      apiRequest: 'POST /api/login {"email":"member@example.test","password":"valid-fixture-password"}',
      apiResponse: 'HTTP 200 {"session":"fixture-session","userId":"u-001"}',
      observedAt: '2026-06-11T09:00:00.000Z',
      environment: { name: 'offline-fixture', version: 'static-example' },
      severity: 'none',
      confidence: 'high',
      limitations: ['Static API response sample; not produced by a live system in this phase.'],
    },
    {
      id: 'EV-SNS-CREATE-NOTE-PASS',
      testCaseId: 'TC-SNS-CREATE-NOTE',
      testScope: 'note CRUD create',
      executionMethod: 'human observation fixture',
      executorType: 'human',
      rawResult: 'pass',
      evidenceSource: 'offline fixture human observation',
      evidenceSummary: 'Observer recorded that a logged-in user created a note and saw it in the note list.',
      observedAt: '2026-06-11T09:05:00.000Z',
      environment: { name: 'offline-fixture', browser: 'fixture-browser' },
      severity: 'none',
      confidence: 'medium',
      limitations: ['Human observation is static fixture data and does not prove a current deployment.'],
    },
    {
      id: 'EV-SNS-SEARCH-PASS',
      testCaseId: 'TC-SNS-SEARCH',
      testScope: 'search title body',
      executionMethod: 'static API response sample',
      executorType: 'api',
      rawResult: 'pass',
      evidenceSource: 'offline fixture API sample',
      evidenceSummary: 'GET /api/notes/search?q=roadmap returned the expected note title and body excerpt.',
      apiRequest: 'GET /api/notes/search?q=roadmap',
      apiResponse: 'HTTP 200 {"items":[{"id":"n-101","title":"Roadmap","excerpt":"Phase plan"}]}',
      observedAt: '2026-06-11T09:10:00.000Z',
      environment: { name: 'offline-fixture' },
      severity: 'none',
      confidence: 'high',
      limitations: ['Static API response sample; not produced by a live system in this phase.'],
    },
    {
      id: 'EV-SNS-PRIVATE-ACCESS-FAIL',
      testCaseId: 'TC-SNS-AUTHZ-PRIVATE-NOTE',
      testScope: 'authorization private data',
      executionMethod: 'static API response sample',
      executorType: 'api',
      rawResult: 'fail',
      evidenceSource: 'offline fixture API sample',
      evidenceSummary: 'Unauthorized user accessed another user private note and received HTTP 200 with private content.',
      apiRequest: 'GET /api/notes/private/n-777 as user u-002',
      apiResponse: 'HTTP 200 {"id":"n-777","visibility":"private","ownerId":"u-001","body":"private fixture text"}',
      observedAt: '2026-06-11T09:15:00.000Z',
      environment: { name: 'offline-fixture' },
      severity: 'P0',
      confidence: 'high',
      limitations: ['Static failure sample; it is a deterministic fixture for permission-risk validation.'],
    },
    {
      id: 'EV-SNS-UPLOAD-LIMIT-FAIL',
      testCaseId: 'TC-SNS-UPLOAD-LIMIT',
      testScope: 'file upload limits',
      executionMethod: 'human observation fixture',
      executorType: 'human',
      rawResult: 'fail',
      evidenceSource: 'offline fixture human observation',
      evidenceSummary: 'A 30 MB attachment was rejected but no clear file size or type error was shown to the user.',
      observedAt: '2026-06-11T09:20:00.000Z',
      environment: { name: 'offline-fixture', browser: 'fixture-browser' },
      severity: 'P2',
      confidence: 'medium',
      limitations: ['Boundary behavior is represented by static fixture text only.'],
    },
    {
      id: 'EV-SNS-RESTORE-NO-RECORD',
      testCaseId: 'TC-SNS-RESTORE-PROCEDURE',
      testScope: 'backup restore',
      executionMethod: 'config review fixture',
      executorType: 'config_review',
      rawResult: 'fail',
      evidenceSource: 'offline fixture maintenance checklist',
      evidenceSummary: 'Backup schedule is described, but no restore drill record, source backup, or verification result is available.',
      observedAt: '2026-06-11T09:25:00.000Z',
      environment: { name: 'offline-fixture' },
      severity: 'P1',
      confidence: 'medium',
      limitations: ['Config review cannot prove live recovery behavior.'],
    },
    {
      id: 'EV-SNS-BACKUP-ORAL-CLAIM',
      testCaseId: 'TC-SNS-BACKUP-CLAIM',
      testScope: 'backup',
      executionMethod: 'oral statement fixture',
      executorType: 'human',
      rawResult: 'inconclusive',
      evidenceSource: 'offline fixture interview note',
      evidenceSummary: 'Operator said the system should be backed up daily, but no artifact, schedule record, or restore proof was supplied.',
      observedAt: '2026-06-11T09:30:00.000Z',
      environment: { name: 'offline-fixture' },
      severity: 'unknown',
      confidence: 'low',
      limitations: ['Oral statement does not prove backup execution or restore readiness.'],
    },
    {
      id: 'EV-SNS-LOGGING-AGENT-PASS',
      testCaseId: 'TC-SNS-LOGGING',
      testScope: 'logging failures and permission denials',
      executionMethod: 'agent reasoning over requirements only',
      executorType: 'agent_reasoning',
      rawResult: 'pass',
      evidenceSource: 'offline fixture agent reasoning',
      evidenceSummary: 'Agent reasoning says required failure logs should exist because requirements mention logging.',
      observedAt: '2026-06-11T09:35:00.000Z',
      environment: { name: 'offline-fixture' },
      severity: 'none',
      confidence: 'low',
      limitations: ['This item intentionally verifies that agent_reasoning + pass is downgraded.'],
    },
  ],
  existingDefects,
  notes: [
    'This fixture is only for offline deterministic pipeline validation.',
    'No item in this fixture is a real system test result.',
  ],
  options: {
    includeOpsChecklist: true,
    includeNegativeCases: true,
    includePermissionChecks: true,
    generateReport: true,
    generateRegressionSuggestions: true,
    generateReleaseRecommendation: true,
  },
};

export const smallNoteSystemFixture: OfflineScenarioFixture = {
  id: 'small-note-system',
  name: 'Small Team Notes',
  description: 'Offline fixture for a 10-30 user note system with private notes, sharing, search, attachment upload, backup/restore, logging, and admin permissions.',
  input: smallNoteSystemOrchestrationInput,
  expectedCharacteristics: {
    minimumAcceptancePoints: 8,
    minimumTestCases: 8,
    minimumEvidence: 8,
    expectedSeverityValues: ['P0', 'P2', 'unknown'],
    expectedReleaseRecommendation: 'blocked',
    requiresDowngradedAgentReasoning: true,
    requiresPermissionRisk: true,
    requiresOpsRisk: true,
    requiresReport: true,
    requiresAuditDrafts: true,
  },
};
